version: '2'
services:
    nginx:
        image: viniciusmattosrj/nginx
        container_name: nginx_1
        restart: always
        ports:
            - "80:80"
        volumes:
            - ../docker/nginx_conf:/etc/nginx/conf.d
        volumes_from:
            - php:rw

    php:
        image: viniciusmattosrj/php:5.6
        command: bash -c "sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini
                    && sed -i 's/;default_charset = \"UTF-8\"/default_charset = \"ISO-8859-1\"/' /usr/local/etc/php/php.ini
                    && sed -i \"s/max_execution_time = 30/max_execution_time = 80000000/\" /usr/local/etc/php/php.ini
                    && sed -i \"s/error_reporting = E_ALL/error_reporting = E_ALL \& \~E_NOTICE \& \~E_STRICT \& \~E_DEPRECATED/\" /usr/local/etc/php/php.ini
                    && php-fpm"
        container_name: php_1
        environment:
            - XDEBUG_CONFIG=remote_host=172.17.0.1
            - PHP_IDE_CONFIG=serverName=Local
        volumes:
            - ../ws_php:/var/www/html
            - ~/.ssh:/root/.ssh

    postgres:
        image: viniciusmattosrj/postgres:9.4
        container_name: postgres_1
        environment:
            - POSTGRES_USER=webadm
            - POSTGRES_PASSWORD=A123456
        ports:
            - "5432:5432"
        volumes:
            - ../dump:/var/lib/postgresql/sqlscript/
            - ../volumes/postgres:/var/lib/postgresql/data

    pgadmin:
        image: viniciusmattosrj/pgadmin:4.1.2
        ports:
            - "5050:5050"
        volumes:
            - ../volumes/pgadmin/config:/pgadmin/config
            - ../volumes/pgadmin/storage:/pgadmin/storage
        links:
            - postgres:localhost_postgres

    gearman:
        image: viniciusmattosrj/gearman:1.0.6
        container_name: gearman_1
        restart: always
        ports:
            - "4730:4730"